package agh.cs.evolution;

public enum Command {
    EXIT, HELP, RUN, ERROR, RESET, SETMAPSIZE, RESETSETTINGS, SET_ANIMAL_ENERGY_LOSS,
    SET_ANIMAL_ENERGY_GAIN, SET_ANIMAL_ENERGY_TO_REPRODUCE, SET_ANIMAL_AGE_TO_REPRODUCE,
    RESET_ANIMAL_SETTINGS, RESET_MAP_SETTINGS, DISPLAY_SETTINGS
}
